- ClientId: client-credentials-mock-client
  ClientSecrets: [client-credentials-mock-client-secret]
  Description: Client for client credentials flow
  AllowedGrantTypes:
    # - client_credentials
    # - implicit
    - authorization_code
  # https://github.com/Soluto/oidc-server-mock/issues/46#issuecomment-704963181
  RequireClientSecret: false
  AllowAccessTokensViaBrowser: true
  AllowedScopes:
    - openid
    - profile
    - email
  ClientClaimsPrefix: ''
  RedirectUris:
    - https://selvbetjening.local.itkdev.dk/openid-connect/generic
    - '*'
  # https://github.com/Soluto/oidc-server-mock/issues/46#issuecomment-704845375
  RequirePkce: false
  Claims:
    - Type: string_claim
      Value: string_claim_value
      ValueType: string
    - Type: json_claim
      Value: '["value1", "value2"]'
      ValueType: json
