version: "3"

networks:
  organisation_api:
    external: true
    name: serviceplatformen_organisation_api_app
  frontend:
    external: true
  app:
    driver: bridge
    internal: false


services:
  phpfpm:
    networks:
      - organisation_api
    environment:
      - PHP_MAX_EXECUTION_TIME=30
      - PHP_MEMORY_LIMIT=512M
      - PHP_POST_MAX_SIZE=11M
      - PHP_UPLOAD_MAX_FILESIZE=10M
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
      - PHP_PM_TYPE=static
      - PHP_PM_MAX_CHILDREN=30

