<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\webform\WebformInterface;
use Drupal\Core\Session\AccountInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the webform add form.
 */
function os2forms_permissions_by_term_form_webform_add_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('os2forms_permissions_by_term.helper')->webformAlter($form, $form_state, 'add');
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Alter the webform settings form.
 */
function os2forms_permissions_by_term_form_webform_settings_form_alter(array &$form, FormStateInterface $form_state, $form_id) {
  \Drupal::service('os2forms_permissions_by_term.helper')->webformAlter($form, $form_state, 'settings');
}

/**
 * Implements hook_ENTITY_TYPE_access() for webform entities.
 *
 * Deny access to webforms based on permissions_by_term.
 */
function os2forms_permissions_by_term_webform_access(WebformInterface $webform, $operation, AccountInterface $account) {
  return \Drupal::service('os2forms_permissions_by_term.helper')->webformAccess($webform, $operation, $account);
}
