<?php

/**
 * @file
 * Module file for the os2forms_email module.
 */

use Drupal\os2forms_email\Plugin\WebformHandler\OS2FormsEmailWebformHandler;

/**
 * Implements hook_ELEMENT_info_alter().
 *
 * Overrides default webform email handler with OS2FormsEmailWebformHandler.
 */
function os2forms_email_webform_handler_info_alter(array &$handlers): void {
  $handlers['email']['class'] = OS2FormsEmailWebformHandler::class;
}
