<?php

/**
 * @file
 * Module file for the os2forms_selvbetjening module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\os2forms_selvbetjening\Helper\FormHelper;

/**
 * Implements hook_form_alter().
 *
 * Allows altering of forms.
 */
function os2forms_selvbetjening_form_alter(array &$form, FormStateInterface $form_state, string $form_id) {
  Drupal::service(FormHelper::class)->formAlter($form, $form_state, $form_id);

  // Set out to edit maestro field edit ajax modal.
  if ($form_id === 'template_edit_task') {
    if (isset($form['spv']['method']['#options']['bycontentfunction'])) {
      $form['spv']['method']['#options']['bycontentfunction'] .= t('. Read more: <a href="https://os2forms.os2.eu/variabler-i-flow" target="_blank">https://os2forms.os2.eu/variabler-i-flow</a>');
    }
  }
}

/**
 * Implements hook_webform_element_alter().
 */
function os2forms_selvbetjening_webform_element_alter(array &$element, FormStateInterface $form_state, array $context) {
  // Add js-form-item class to webform_more element to expose them to form
  // states (element conditions).
  if ('webform_more' === $element['#type']) {
    $element['#attributes']['class'][] = 'js-form-item';
  }

  if ('os2forms_dawa_address' === $element['#type']) {
    $element['#attached']['library'][] = 'os2forms_selvbetjening/dawa_address_autocomplete';
  }
}

/**
 * Implements hook_views_plugins_field_alter().
 */
function os2forms_selvbetjening_views_plugins_field_alter(array &$plugins) {
  if (array_key_exists('author_assignment_node_bulk_form', $plugins)) {
    $plugins['author_assignment_node_bulk_form']['id'] .= '_override';
    $plugins['author_assignment_node_bulk_form']['class'] = 'Drupal\os2forms_selvbetjening\Plugin\views\field\AuthorAssignmentNodeBulkFormOverride';
    $plugins['author_assignment_node_bulk_form']['provider'] = 'os2forms_selvbetjening';
  }
}
