<?php

/**
 * @file
 * Contains hooks related to OS2Forms REST API module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\os2forms_rest_api\WebformHelper;

/**
 * Implements hook_webform_third_party_settings_form_alter().
 *
 * @see WebformHelper::webformThirdPartySettingsFormAlter()
 */
function os2forms_rest_api_webform_third_party_settings_form_alter(array &$form, FormStateInterface $form_state) {
  \Drupal::service(WebformHelper::class)->webformThirdPartySettingsFormAlter($form, $form_state);
}
