<?php

use Drupal\os2forms_webform_list\CustomMaestroTemplateEntityListBuilder;
use Drupal\os2forms_webform_list\CustomWebformEntityListBuilder;

/**
 * @file
 * Contains hooks related to OS2Forms webform list module.
 */

/**
 * Implements hook_entity_type_alter().
 *
 * Change entitytypes.
 */
function os2forms_webform_list_entity_type_alter(array &$entity_types) {
  /** @var \Drupal\Core\Entity\EntityTypeInterface[] $entity_types */
  // Define a new list builder classes.
  $entity_types['webform']->setListBuilderClass(CustomWebformEntityListBuilder::class);
  $entity_types['maestro_template']->setListBuilderClass(CustomMaestroTemplateEntityListBuilder::class);
}
