<?php

/**
 * Implements hook_honeypot_form_protections_alter().
 *
 * Disable honeypot on the OpenID Connect login form.
 */
function itkdev_openid_connect_honeypot_form_protections_alter(array &$options, array $form) {
  if ('openid_connect_login_form' === ($form['form_id']['#value'] ?? NULL)) {
    $options = [];
  }
}

/**
  * Implements hook_user_default_page_login_ignore_whitelist_alter().
  */
function itkdev_openid_connect_user_default_page_login_ignore_whitelist_alter(array &$ignored_routes) {
  // Check if we're in the OpenID Connect login flow.
  $current_route = \Drupal::service('current_route_match')->getRouteName();
  if ('openid_connect.redirect_controller_redirect' === $current_route) {
    // Check if OpenID Connect has stored a redirect destination.
    $destination = \Drupal::service('openid_connect.session')->retrieveDestination(FALSE);
    if (isset($destination['destination'])) {
      // OpenID Connect has a redirect. User default page should ignore the
      // current route.
      $ignored_routes[] = $current_route;
    }
  }
}
